/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface CollectionsReport {
  'totalCollections' : number,
  'paymentCount' : bigint,
}
export interface CompanySettings {
  'lowStockThreshold' : number,
  'address' : string,
  'companyName' : string,
  'phone' : string,
  'taxRate' : number,
}
export interface Customer {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
  'address' : string,
  'phone' : string,
}
export interface CustomerStatement {
  'balance' : number,
  'payments' : Array<Payment>,
  'customer' : Customer,
  'invoices' : Array<Invoice>,
}
export interface Dashboard {
  'todaySales' : number,
  'recentInvoices' : Array<Invoice>,
  'monthSales' : number,
  'lowStockProducts' : Array<Product>,
  'monthCollections' : number,
  'todayCollections' : number,
  'recentPayments' : Array<Payment>,
  'totalDebts' : number,
}
export interface DebtsReport {
  'totalDebts' : number,
  'customers' : Array<CustomerStatement>,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface InventoryMovement {
  'id' : bigint,
  'createdAt' : Timestamp,
  'productId' : bigint,
  'movementType' : MovementType,
  'quantity' : number,
}
export interface Invoice {
  'id' : bigint,
  'tax' : number,
  'total' : number,
  'paymentStatus' : PaymentStatus,
  'createdAt' : Timestamp,
  'discount' : number,
  'customerId' : bigint,
  'items' : Array<InvoiceItem>,
  'subtotal' : number,
}
export interface InvoiceItem {
  'lineTotal' : number,
  'productId' : bigint,
  'productName' : string,
  'quantity' : number,
  'unitPrice' : number,
}
export type MovementType = { 'add' : null } |
  { 'sale' : null } |
  { 'adjust' : null } |
  { 'refund' : null };
export interface Payment {
  'id' : bigint,
  'method' : PaymentMethod,
  'createdAt' : Timestamp,
  'invoiceId' : [] | [bigint],
  'customerId' : bigint,
  'amount' : number,
}
export type PaymentMethod = { 'other' : null } |
  { 'cash' : null } |
  { 'check' : null } |
  { 'instapay' : null } |
  { 'bankTransfer' : null };
export type PaymentStatus = { 'paid' : null } |
  { 'unpaid' : null } |
  { 'partial' : null };
export interface Product {
  'id' : bigint,
  'purchasePrice' : number,
  'lowStockThreshold' : number,
  'name' : string,
  'unit' : Unit,
  'description' : string,
  'isActive' : boolean,
  'quantity' : number,
  'salePrice' : number,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SalesReport {
  'invoiceCount' : bigint,
  'totalSales' : number,
  'itemsSold' : number,
}
export type Timestamp = bigint;
export type Unit = { 'other' : null } |
  { 'gram' : null } |
  { 'kilo' : null } |
  { 'unit' : null } |
  { 'carton' : null } |
  { 'piece' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addCustomer' : ActorMethod<[string, string, string], bigint>,
  'addPayment' : ActorMethod<
    [bigint, [] | [bigint], number, PaymentMethod],
    bigint
  >,
  'addProduct' : ActorMethod<
    [string, string, number, number, number, Unit, number],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canManageProducts' : ActorMethod<[], boolean>,
  'createInvoice' : ActorMethod<
    [bigint, Array<InvoiceItem>, number, number],
    bigint
  >,
  'deactivateCustomer' : ActorMethod<[bigint], undefined>,
  'deactivateProduct' : ActorMethod<[bigint], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCollectionsReport' : ActorMethod<
    [Timestamp, Timestamp],
    CollectionsReport
  >,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getCustomerStatement' : ActorMethod<[bigint], CustomerStatement>,
  'getDashboard' : ActorMethod<[], Dashboard>,
  'getDebtsReport' : ActorMethod<[], DebtsReport>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getLowStockProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getSalesReport' : ActorMethod<[Timestamp, Timestamp], SalesReport>,
  'getSettings' : ActorMethod<[], CompanySettings>,
  'grantProductPermission' : ActorMethod<[Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCustomers' : ActorMethod<[], Array<Customer>>,
  'listInventory' : ActorMethod<[], Array<InventoryMovement>>,
  'listInvoices' : ActorMethod<[], Array<Invoice>>,
  'listPayments' : ActorMethod<[], Array<Payment>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'recordMovement' : ActorMethod<[bigint, MovementType, number], undefined>,
  'revokeProductPermission' : ActorMethod<[Principal], undefined>,
  'schema' : ActorMethod<[], string>,
  'updateCustomer' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateInvoice' : ActorMethod<
    [bigint, bigint, Array<InvoiceItem>, number, number],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, number, number, number, Unit, number],
    undefined
  >,
  'updateSettings' : ActorMethod<
    [string, string, string, number, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];