/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const PaymentMethod = IDL.Variant({
  'other' : IDL.Null,
  'cash' : IDL.Null,
  'check' : IDL.Null,
  'instapay' : IDL.Null,
  'bankTransfer' : IDL.Null,
});
export const Unit = IDL.Variant({
  'other' : IDL.Null,
  'gram' : IDL.Null,
  'kilo' : IDL.Null,
  'unit' : IDL.Null,
  'carton' : IDL.Null,
  'piece' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InvoiceItem = IDL.Record({
  'lineTotal' : IDL.Float64,
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Float64,
  'unitPrice' : IDL.Float64,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Timestamp = IDL.Int;
export const CollectionsReport = IDL.Record({
  'totalCollections' : IDL.Float64,
  'paymentCount' : IDL.Nat,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'method' : PaymentMethod,
  'createdAt' : Timestamp,
  'invoiceId' : IDL.Opt(IDL.Nat),
  'customerId' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const PaymentStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
  'partial' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'tax' : IDL.Float64,
  'total' : IDL.Float64,
  'paymentStatus' : PaymentStatus,
  'createdAt' : Timestamp,
  'discount' : IDL.Float64,
  'customerId' : IDL.Nat,
  'items' : IDL.Vec(InvoiceItem),
  'subtotal' : IDL.Float64,
});
export const CustomerStatement = IDL.Record({
  'balance' : IDL.Float64,
  'payments' : IDL.Vec(Payment),
  'customer' : Customer,
  'invoices' : IDL.Vec(Invoice),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'purchasePrice' : IDL.Float64,
  'lowStockThreshold' : IDL.Float64,
  'name' : IDL.Text,
  'unit' : Unit,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'quantity' : IDL.Float64,
  'salePrice' : IDL.Float64,
});
export const Dashboard = IDL.Record({
  'todaySales' : IDL.Float64,
  'recentInvoices' : IDL.Vec(Invoice),
  'monthSales' : IDL.Float64,
  'lowStockProducts' : IDL.Vec(Product),
  'monthCollections' : IDL.Float64,
  'todayCollections' : IDL.Float64,
  'recentPayments' : IDL.Vec(Payment),
  'totalDebts' : IDL.Float64,
});
export const DebtsReport = IDL.Record({
  'totalDebts' : IDL.Float64,
  'customers' : IDL.Vec(CustomerStatement),
});
export const SalesReport = IDL.Record({
  'invoiceCount' : IDL.Nat,
  'totalSales' : IDL.Float64,
  'itemsSold' : IDL.Float64,
});
export const CompanySettings = IDL.Record({
  'lowStockThreshold' : IDL.Float64,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
  'taxRate' : IDL.Float64,
});
export const MovementType = IDL.Variant({
  'add' : IDL.Null,
  'sale' : IDL.Null,
  'adjust' : IDL.Null,
  'refund' : IDL.Null,
});
export const InventoryMovement = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Timestamp,
  'productId' : IDL.Nat,
  'movementType' : MovementType,
  'quantity' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addPayment' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Float64, PaymentMethod],
      [IDL.Nat],
      [],
    ),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        Unit,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canManageProducts' : IDL.Func([], [IDL.Bool], ['query']),
  'createInvoice' : IDL.Func(
      [IDL.Nat, IDL.Vec(InvoiceItem), IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'deactivateCustomer' : IDL.Func([IDL.Nat], [], []),
  'deactivateProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCollectionsReport' : IDL.Func(
      [Timestamp, Timestamp],
      [CollectionsReport],
      ['query'],
    ),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getCustomerStatement' : IDL.Func([IDL.Nat], [CustomerStatement], ['query']),
  'getDashboard' : IDL.Func([], [Dashboard], ['query']),
  'getDebtsReport' : IDL.Func([], [DebtsReport], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
  'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getSalesReport' : IDL.Func([Timestamp, Timestamp], [SalesReport], ['query']),
  'getSettings' : IDL.Func([], [CompanySettings], ['query']),
  'grantProductPermission' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listInventory' : IDL.Func([], [IDL.Vec(InventoryMovement)], ['query']),
  'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'listPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'recordMovement' : IDL.Func([IDL.Nat, MovementType, IDL.Float64], [], []),
  'revokeProductPermission' : IDL.Func([IDL.Principal], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateCustomer' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateInvoice' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(InvoiceItem), IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        Unit,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'updateSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const PaymentMethod = IDL.Variant({
    'other' : IDL.Null,
    'cash' : IDL.Null,
    'check' : IDL.Null,
    'instapay' : IDL.Null,
    'bankTransfer' : IDL.Null,
  });
  const Unit = IDL.Variant({
    'other' : IDL.Null,
    'gram' : IDL.Null,
    'kilo' : IDL.Null,
    'unit' : IDL.Null,
    'carton' : IDL.Null,
    'piece' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InvoiceItem = IDL.Record({
    'lineTotal' : IDL.Float64,
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Float64,
    'unitPrice' : IDL.Float64,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Timestamp = IDL.Int;
  const CollectionsReport = IDL.Record({
    'totalCollections' : IDL.Float64,
    'paymentCount' : IDL.Nat,
  });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'method' : PaymentMethod,
    'createdAt' : Timestamp,
    'invoiceId' : IDL.Opt(IDL.Nat),
    'customerId' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const PaymentStatus = IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'partial' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'tax' : IDL.Float64,
    'total' : IDL.Float64,
    'paymentStatus' : PaymentStatus,
    'createdAt' : Timestamp,
    'discount' : IDL.Float64,
    'customerId' : IDL.Nat,
    'items' : IDL.Vec(InvoiceItem),
    'subtotal' : IDL.Float64,
  });
  const CustomerStatement = IDL.Record({
    'balance' : IDL.Float64,
    'payments' : IDL.Vec(Payment),
    'customer' : Customer,
    'invoices' : IDL.Vec(Invoice),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'purchasePrice' : IDL.Float64,
    'lowStockThreshold' : IDL.Float64,
    'name' : IDL.Text,
    'unit' : Unit,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'quantity' : IDL.Float64,
    'salePrice' : IDL.Float64,
  });
  const Dashboard = IDL.Record({
    'todaySales' : IDL.Float64,
    'recentInvoices' : IDL.Vec(Invoice),
    'monthSales' : IDL.Float64,
    'lowStockProducts' : IDL.Vec(Product),
    'monthCollections' : IDL.Float64,
    'todayCollections' : IDL.Float64,
    'recentPayments' : IDL.Vec(Payment),
    'totalDebts' : IDL.Float64,
  });
  const DebtsReport = IDL.Record({
    'totalDebts' : IDL.Float64,
    'customers' : IDL.Vec(CustomerStatement),
  });
  const SalesReport = IDL.Record({
    'invoiceCount' : IDL.Nat,
    'totalSales' : IDL.Float64,
    'itemsSold' : IDL.Float64,
  });
  const CompanySettings = IDL.Record({
    'lowStockThreshold' : IDL.Float64,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
    'taxRate' : IDL.Float64,
  });
  const MovementType = IDL.Variant({
    'add' : IDL.Null,
    'sale' : IDL.Null,
    'adjust' : IDL.Null,
    'refund' : IDL.Null,
  });
  const InventoryMovement = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Timestamp,
    'productId' : IDL.Nat,
    'movementType' : MovementType,
    'quantity' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addCustomer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addPayment' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Float64, PaymentMethod],
        [IDL.Nat],
        [],
      ),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          Unit,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canManageProducts' : IDL.Func([], [IDL.Bool], ['query']),
    'createInvoice' : IDL.Func(
        [IDL.Nat, IDL.Vec(InvoiceItem), IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'deactivateCustomer' : IDL.Func([IDL.Nat], [], []),
    'deactivateProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCollectionsReport' : IDL.Func(
        [Timestamp, Timestamp],
        [CollectionsReport],
        ['query'],
      ),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getCustomerStatement' : IDL.Func(
        [IDL.Nat],
        [CustomerStatement],
        ['query'],
      ),
    'getDashboard' : IDL.Func([], [Dashboard], ['query']),
    'getDebtsReport' : IDL.Func([], [DebtsReport], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
    'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getSalesReport' : IDL.Func(
        [Timestamp, Timestamp],
        [SalesReport],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [CompanySettings], ['query']),
    'grantProductPermission' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listInventory' : IDL.Func([], [IDL.Vec(InventoryMovement)], ['query']),
    'listInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'listPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'recordMovement' : IDL.Func([IDL.Nat, MovementType, IDL.Float64], [], []),
    'revokeProductPermission' : IDL.Func([IDL.Principal], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateInvoice' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(InvoiceItem), IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          Unit,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'updateSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };