/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface InvoiceItem {
    lineTotal: number;
    productId: bigint;
    productName: string;
    quantity: number;
    unitPrice: number;
}
export type Timestamp = bigint;
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Payment {
    id: bigint;
    method: PaymentMethod;
    createdAt: Timestamp;
    invoiceId?: bigint;
    customerId: bigint;
    amount: number;
}
export interface Invoice {
    id: bigint;
    tax: number;
    total: number;
    paymentStatus: PaymentStatus;
    createdAt: Timestamp;
    discount: number;
    customerId: bigint;
    items: Array<InvoiceItem>;
    subtotal: number;
}
export interface CustomerStatement {
    balance: number;
    payments: Array<Payment>;
    customer: Customer;
    invoices: Array<Invoice>;
}
export interface Customer {
    id: bigint;
    name: string;
    isActive: boolean;
    address: string;
    phone: string;
}
export interface CollectionsReport {
    totalCollections: number;
    paymentCount: bigint;
}
export interface InventoryMovement {
    id: bigint;
    createdAt: Timestamp;
    productId: bigint;
    movementType: MovementType;
    quantity: number;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface SalesReport {
    invoiceCount: bigint;
    totalSales: number;
    itemsSold: number;
}
export interface DebtsReport {
    totalDebts: number;
    customers: Array<CustomerStatement>;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface Dashboard {
    todaySales: number;
    recentInvoices: Array<Invoice>;
    monthSales: number;
    lowStockProducts: Array<Product>;
    monthCollections: number;
    todayCollections: number;
    recentPayments: Array<Payment>;
    totalDebts: number;
}
export interface CompanySettings {
    lowStockThreshold: number;
    address: string;
    companyName: string;
    phone: string;
    taxRate: number;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface Product {
    id: bigint;
    purchasePrice: number;
    lowStockThreshold: number;
    name: string;
    unit: Unit;
    description: string;
    isActive: boolean;
    quantity: number;
    salePrice: number;
}
export enum MovementType {
    add = "add",
    sale = "sale",
    adjust = "adjust",
    refund = "refund"
}
export enum PaymentMethod {
    other = "other",
    cash = "cash",
    check = "check",
    instapay = "instapay",
    bankTransfer = "bankTransfer"
}
export enum PaymentStatus {
    paid = "paid",
    unpaid = "unpaid",
    partial = "partial"
}
export enum Unit {
    other = "other",
    gram = "gram",
    kilo = "kilo",
    unit = "unit",
    carton = "carton",
    piece = "piece"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addCustomer(name: string, phone: string, address: string): Promise<bigint>;
    addPayment(customerId: bigint, invoiceId: bigint | null, amount: number, method: PaymentMethod): Promise<bigint>;
    addProduct(name: string, description: string, salePrice: number, purchasePrice: number, quantity: number, unit: Unit, lowStockThreshold: number): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    canManageProducts(): Promise<boolean>;
    createInvoice(customerId: bigint, items: Array<InvoiceItem>, discount: number, tax: number): Promise<bigint>;
    deactivateCustomer(id: bigint): Promise<void>;
    deactivateProduct(id: bigint): Promise<void>;
    deleteCustomer(id: bigint): Promise<void>;
    deleteInvoice(id: bigint): Promise<void>;
    deleteProduct(id: bigint): Promise<void>;
    execute(qJson: string): Promise<Result>;
    getCallerUserRole(): Promise<UserRole>;
    getCollectionsReport(start: Timestamp, end: Timestamp): Promise<CollectionsReport>;
    getCustomer(id: bigint): Promise<Customer | null>;
    getCustomerStatement(id: bigint): Promise<CustomerStatement>;
    getDashboard(): Promise<Dashboard>;
    getDebtsReport(): Promise<DebtsReport>;
    getInvoice(id: bigint): Promise<Invoice | null>;
    getLowStockProducts(): Promise<Array<Product>>;
    getProduct(id: bigint): Promise<Product | null>;
    getSalesReport(start: Timestamp, end: Timestamp): Promise<SalesReport>;
    getSettings(): Promise<CompanySettings>;
    grantProductPermission(user: Principal): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listCustomers(): Promise<Array<Customer>>;
    listInventory(): Promise<Array<InventoryMovement>>;
    listInvoices(): Promise<Array<Invoice>>;
    listPayments(): Promise<Array<Payment>>;
    listProducts(): Promise<Array<Product>>;
    recordMovement(productId: bigint, movementType: MovementType, quantity: number): Promise<void>;
    revokeProductPermission(user: Principal): Promise<void>;
    schema(): Promise<string>;
    updateCustomer(id: bigint, name: string, phone: string, address: string): Promise<void>;
    updateInvoice(id: bigint, customerId: bigint, items: Array<InvoiceItem>, discount: number, tax: number): Promise<void>;
    updateProduct(id: bigint, name: string, description: string, salePrice: number, purchasePrice: number, quantity: number, unit: Unit, lowStockThreshold: number): Promise<void>;
    updateSettings(companyName: string, address: string, phone: string, taxRate: number, lowStockThreshold: number): Promise<void>;
}
import type { Cell as _Cell, Customer as _Customer, CustomerStatement as _CustomerStatement, Dashboard as _Dashboard, DebtsReport as _DebtsReport, Error as _Error, InventoryMovement as _InventoryMovement, Invoice as _Invoice, InvoiceItem as _InvoiceItem, MovementType as _MovementType, Payment as _Payment, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, Product as _Product, Result as _Result, Result__1 as _Result__1, Timestamp as _Timestamp, Unit as _Unit, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addCustomer(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1, arg2);
            return result;
        }
    }
    async addPayment(arg0: bigint, arg1: bigint | null, arg2: number, arg3: PaymentMethod): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_PaymentMethod_n6(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_PaymentMethod_n6(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: number, arg3: number, arg4: number, arg5: Unit, arg6: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, to_candid_Unit_n8(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, to_candid_Unit_n8(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async canManageProducts(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canManageProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canManageProducts();
            return result;
        }
    }
    async createInvoice(arg0: bigint, arg1: Array<InvoiceItem>, arg2: number, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deactivateCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateCustomer(arg0);
            return result;
        }
    }
    async deactivateProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateProduct(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollectionsReport(arg0: Timestamp, arg1: Timestamp): Promise<CollectionsReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollectionsReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollectionsReport(arg0, arg1);
            return result;
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerStatement(arg0: bigint): Promise<CustomerStatement> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerStatement(arg0);
                return from_candid_CustomerStatement_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerStatement(arg0);
            return from_candid_CustomerStatement_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboard(): Promise<Dashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard();
                return from_candid_Dashboard_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard();
            return from_candid_Dashboard_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDebtsReport(): Promise<DebtsReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getDebtsReport();
                return from_candid_DebtsReport_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDebtsReport();
            return from_candid_DebtsReport_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockProducts();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockProducts();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSalesReport(arg0: Timestamp, arg1: Timestamp): Promise<SalesReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesReport(arg0, arg1);
            return result;
        }
    }
    async getSettings(): Promise<CompanySettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async grantProductPermission(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantProductPermission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantProductPermission(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomers();
            return result;
        }
    }
    async listInventory(): Promise<Array<InventoryMovement>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInventory();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInventory();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoices();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoices();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPayments();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPayments();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordMovement(arg0: bigint, arg1: MovementType, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordMovement(arg0, to_candid_MovementType_n53(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordMovement(arg0, to_candid_MovementType_n53(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async revokeProductPermission(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeProductPermission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeProductPermission(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async updateCustomer(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateInvoice(arg0: bigint, arg1: bigint, arg2: Array<InvoiceItem>, arg3: number, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: Unit, arg7: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Unit_n8(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Unit_n8(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async updateSettings(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_Cell_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerStatement_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerStatement): CustomerStatement {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Dashboard_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Dashboard): Dashboard {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_DebtsReport_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DebtsReport): DebtsReport {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryMovement_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryMovement): InventoryMovement {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_MovementType_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MovementType): MovementType {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Unit_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Unit): Unit {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n14(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n18(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: number;
    payments: Array<_Payment>;
    customer: _Customer;
    invoices: Array<_Invoice>;
}): {
    balance: number;
    payments: Array<Payment>;
    customer: Customer;
    invoices: Array<Invoice>;
} {
    return {
        balance: value.balance,
        payments: from_candid_vec_n25(_uploadFile, _downloadFile, value.payments),
        customer: value.customer,
        invoices: from_candid_vec_n31(_uploadFile, _downloadFile, value.invoices)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    method: _PaymentMethod;
    createdAt: _Timestamp;
    invoiceId: [] | [bigint];
    customerId: bigint;
    amount: number;
}): {
    id: bigint;
    method: PaymentMethod;
    createdAt: Timestamp;
    invoiceId?: bigint;
    customerId: bigint;
    amount: number;
} {
    return {
        id: value.id,
        method: from_candid_PaymentMethod_n28(_uploadFile, _downloadFile, value.method),
        createdAt: value.createdAt,
        invoiceId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.invoiceId)),
        customerId: value.customerId,
        amount: value.amount
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tax: number;
    total: number;
    paymentStatus: _PaymentStatus;
    createdAt: _Timestamp;
    discount: number;
    customerId: bigint;
    items: Array<_InvoiceItem>;
    subtotal: number;
}): {
    id: bigint;
    tax: number;
    total: number;
    paymentStatus: PaymentStatus;
    createdAt: Timestamp;
    discount: number;
    customerId: bigint;
    items: Array<InvoiceItem>;
    subtotal: number;
} {
    return {
        id: value.id,
        tax: value.tax,
        total: value.total,
        paymentStatus: from_candid_PaymentStatus_n34(_uploadFile, _downloadFile, value.paymentStatus),
        createdAt: value.createdAt,
        discount: value.discount,
        customerId: value.customerId,
        items: value.items,
        subtotal: value.subtotal
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    todaySales: number;
    recentInvoices: Array<_Invoice>;
    monthSales: number;
    lowStockProducts: Array<_Product>;
    monthCollections: number;
    todayCollections: number;
    recentPayments: Array<_Payment>;
    totalDebts: number;
}): {
    todaySales: number;
    recentInvoices: Array<Invoice>;
    monthSales: number;
    lowStockProducts: Array<Product>;
    monthCollections: number;
    todayCollections: number;
    recentPayments: Array<Payment>;
    totalDebts: number;
} {
    return {
        todaySales: value.todaySales,
        recentInvoices: from_candid_vec_n31(_uploadFile, _downloadFile, value.recentInvoices),
        monthSales: value.monthSales,
        lowStockProducts: from_candid_vec_n38(_uploadFile, _downloadFile, value.lowStockProducts),
        monthCollections: value.monthCollections,
        todayCollections: value.todayCollections,
        recentPayments: from_candid_vec_n25(_uploadFile, _downloadFile, value.recentPayments),
        totalDebts: value.totalDebts
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    purchasePrice: number;
    lowStockThreshold: number;
    name: string;
    unit: _Unit;
    description: string;
    isActive: boolean;
    quantity: number;
    salePrice: number;
}): {
    id: bigint;
    purchasePrice: number;
    lowStockThreshold: number;
    name: string;
    unit: Unit;
    description: string;
    isActive: boolean;
    quantity: number;
    salePrice: number;
} {
    return {
        id: value.id,
        purchasePrice: value.purchasePrice,
        lowStockThreshold: value.lowStockThreshold,
        name: value.name,
        unit: from_candid_Unit_n41(_uploadFile, _downloadFile, value.unit),
        description: value.description,
        isActive: value.isActive,
        quantity: value.quantity,
        salePrice: value.salePrice
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalDebts: number;
    customers: Array<_CustomerStatement>;
}): {
    totalDebts: number;
    customers: Array<CustomerStatement>;
} {
    return {
        totalDebts: value.totalDebts,
        customers: from_candid_vec_n45(_uploadFile, _downloadFile, value.customers)
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    createdAt: _Timestamp;
    productId: bigint;
    movementType: _MovementType;
    quantity: number;
}): {
    id: bigint;
    createdAt: Timestamp;
    productId: bigint;
    movementType: MovementType;
    quantity: number;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        productId: value.productId,
        movementType: from_candid_MovementType_n51(_uploadFile, _downloadFile, value.movementType),
        quantity: value.quantity
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    cash: null;
} | {
    check: null;
} | {
    instapay: null;
} | {
    bankTransfer: null;
}): PaymentMethod {
    return "other" in value ? PaymentMethod.other : "cash" in value ? PaymentMethod.cash : "check" in value ? PaymentMethod.check : "instapay" in value ? PaymentMethod.instapay : "bankTransfer" in value ? PaymentMethod.bankTransfer : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
} | {
    partial: null;
}): PaymentStatus {
    return "paid" in value ? PaymentStatus.paid : "unpaid" in value ? PaymentStatus.unpaid : "partial" in value ? PaymentStatus.partial : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    gram: null;
} | {
    kilo: null;
} | {
    unit: null;
} | {
    carton: null;
} | {
    piece: null;
}): Unit {
    return "other" in value ? Unit.other : "gram" in value ? Unit.gram : "kilo" in value ? Unit.kilo : "unit" in value ? Unit.unit : "carton" in value ? Unit.carton : "piece" in value ? Unit.piece : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    add: null;
} | {
    sale: null;
} | {
    adjust: null;
} | {
    refund: null;
}): MovementType {
    return "add" in value ? MovementType.add : "sale" in value ? MovementType.sale : "adjust" in value ? MovementType.adjust : "refund" in value ? MovementType.refund : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerStatement>): Array<CustomerStatement> {
    return value.map((x)=>from_candid_CustomerStatement_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryMovement>): Array<InventoryMovement> {
    return value.map((x)=>from_candid_InventoryMovement_n49(_uploadFile, _downloadFile, x));
}
function to_candid_MovementType_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MovementType): _MovementType {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Unit_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Unit): _Unit {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MovementType): {
    add: null;
} | {
    sale: null;
} | {
    adjust: null;
} | {
    refund: null;
} {
    return value == MovementType.add ? {
        add: null
    } : value == MovementType.sale ? {
        sale: null
    } : value == MovementType.adjust ? {
        adjust: null
    } : value == MovementType.refund ? {
        refund: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    other: null;
} | {
    cash: null;
} | {
    check: null;
} | {
    instapay: null;
} | {
    bankTransfer: null;
} {
    return value == PaymentMethod.other ? {
        other: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.check ? {
        check: null
    } : value == PaymentMethod.instapay ? {
        instapay: null
    } : value == PaymentMethod.bankTransfer ? {
        bankTransfer: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Unit): {
    other: null;
} | {
    gram: null;
} | {
    kilo: null;
} | {
    unit: null;
} | {
    carton: null;
} | {
    piece: null;
} {
    return value == Unit.other ? {
        other: null
    } : value == Unit.gram ? {
        gram: null
    } : value == Unit.kilo ? {
        kilo: null
    } : value == Unit.unit ? {
        unit: null
    } : value == Unit.carton ? {
        carton: null
    } : value == Unit.piece ? {
        piece: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
